services:
  - type: web
    name: moengage-extractor
    env: docker
    plan: free
    autoDeploy: true
    secretEnvs: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_SERVER_ENABLECORS
        value: "false"
      - key: STREAMLIT_SERVER_ADDRESS
        value: "0.0.0.0"
