services:
  - type: web
    name: moengage-extractor
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_SERVER_ENABLECORS
        value: "false"
      - key: STREAMLIT_SERVER_ADDRESS
        value: "0.0.0.0"
      - key: WORKSPACE
        value: "Collections_TC"
      - key: MOENGAGE_EMAIL
        sync: false
      - key: MOENGAGE_PASSWORD
        sync: false
      - key: DRAFT_IDS
        sync: false
      - key: OTP_CODE
        sync: false
